spring:
  messages:
    basename: errors
  thymeleaf:
    prefix: file:src/main/resources/templates/
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database : mysql
    hibernate.ddl-auto : update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.type: trace